package fatec.poo.view;

import fatec.poo.control.Conexao;
import fatec.poo.control.DaoAPrazo;
import fatec.poo.control.DaoAVista;
import fatec.poo.control.DaoCurso;
import fatec.poo.control.DaoTurma;
import fatec.poo.control.DaoMatricula;
import fatec.poo.control.DaoAluno;

import fatec.poo.model.APrazo;
import fatec.poo.model.AVista;
import fatec.poo.model.Aluno;
import fatec.poo.model.Pessoa;
import fatec.poo.model.Matricula;
import fatec.poo.model.Turma;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 * @author Gabriel Paulino
 * @author 0030481813020
 */
public class GuiAlocarEfetuarMatricula extends javax.swing.JFrame {

    /**
     * Creates new form GuiAlocarEfetuarMatricula
     */
    public GuiAlocarEfetuarMatricula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrPagamento = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rbtAVista = new javax.swing.JRadioButton();
        rbtAPrazo = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPreData = new javax.swing.JFormattedTextField();
        txtDtVencimento = new javax.swing.JFormattedTextField();
        txtNCheque = new javax.swing.JTextField();
        txtTaxaJuros = new javax.swing.JTextField();
        txtAgencia = new javax.swing.JTextField();
        txtQtdeMensalidade = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        txtCPFAluno = new javax.swing.JFormattedTextField();
        lblValor = new javax.swing.JLabel();
        cbxCurso = new javax.swing.JComboBox<>();
        cbxTurma = new javax.swing.JComboBox<>();
        lblNomeAluno = new javax.swing.JLabel();
        txtDataMatricula = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Data Matrícula");

        jLabel2.setText("Curso");

        jLabel3.setText("Turma");

        jLabel4.setText("CPF Aluno");

        jLabel5.setText("Valor");

        jLabel6.setText("Nome");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pagamento"));

        btngrPagamento.add(rbtAVista);
        rbtAVista.setText("À Vista");
        rbtAVista.setEnabled(false);
        rbtAVista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtAVistaActionPerformed(evt);
            }
        });

        btngrPagamento.add(rbtAPrazo);
        rbtAPrazo.setText("Parcelado");
        rbtAPrazo.setEnabled(false);
        rbtAPrazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtAPrazoActionPerformed(evt);
            }
        });

        jLabel7.setText("Agência");

        jLabel8.setText("Qtde. Mensalidades");

        jLabel9.setText("Nº Cheque");

        jLabel10.setText("Tx. Juros (%)");

        jLabel12.setText("Data 1º Vencto.");

        jLabel11.setText("Data Pagto.");

        txtPreData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        txtPreData.setEnabled(false);

        txtDtVencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        txtDtVencimento.setEnabled(false);

        txtNCheque.setEnabled(false);

        txtTaxaJuros.setEnabled(false);

        txtAgencia.setEnabled(false);

        txtQtdeMensalidade.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtAPrazo)
                    .addComponent(rbtAVista))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQtdeMensalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTaxaJuros, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDtVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txtPreData, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAgencia, txtDtVencimento, txtNCheque, txtPreData, txtQtdeMensalidade, txtTaxaJuros});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtAVista)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtPreData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtAPrazo)
                    .addComponent(jLabel12)
                    .addComponent(txtQtdeMensalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addComponent(txtTaxaJuros, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDtVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtAgencia, txtDtVencimento, txtNCheque, txtPreData, txtQtdeMensalidade, txtTaxaJuros});

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Eraser.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.setEnabled(false);
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        try {
            txtCPFAluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPFAluno.setEnabled(false);

        lblValor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        cbxCurso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCursoItemStateChanged(evt);
            }
        });

        cbxTurma.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxTurmaItemStateChanged(evt);
            }
        });
        cbxTurma.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbxTurmaFocusLost(evt);
            }
        });

        lblNomeAluno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtDataMatricula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCPFAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(btnConsultar)
                                .addGap(18, 18, 18)
                                .addComponent(btnInserir)
                                .addGap(18, 18, 18)
                                .addComponent(btnAlterar)
                                .addGap(18, 18, 18)
                                .addComponent(btnExcluir)
                                .addGap(18, 18, 18)
                                .addComponent(btnSair))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 16, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterar, btnConsultar, btnExcluir, btnInserir, btnSair});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbxCurso, cbxTurma, lblValor, txtCPFAluno, txtDataMatricula});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDataMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(cbxTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtCPFAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnSair)
                    .addComponent(btnInserir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbxCurso, cbxTurma, lblNomeAluno, lblValor, txtCPFAluno, txtDataMatricula});

        getAccessibleContext().setAccessibleName("Efetuar Matrícula");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conexao = new Conexao("BD1913014", "BD1913014");
        conexao.setDriver("oracle.jdbc.driver.OracleDriver");
        conexao.setConnectionString("jdbc:oracle:thin:@localhost:1521:xe");
        //conexao.setConnectionString("jdbc:oracle:thin:@apolo:1521:xe");

        daoCurso = new DaoCurso(conexao.conectar());
        daoTurma = new DaoTurma(conexao.conectar());
        daoAluno = new DaoAluno(conexao.conectar());
        daoMatricula = new DaoMatricula(conexao.conectar());
        daoAVista = new DaoAVista(conexao.conectar());
        daoAPrazo = new DaoAPrazo(conexao.conectar());

        ArrayList<String> listaSiglas;
        listaSiglas = daoCurso.listarSiglas();

        for (String siglas : listaSiglas) {
            cbxCurso.addItem(siglas);
        }

        cbxCurso.setSelectedItem(null);
        cbxTurma.setEnabled(false);
        txtCPFAluno.setEnabled(false);
        txtDataMatricula.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        conexao.fecharConexao();
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void cbxCursoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCursoItemStateChanged
        cbxTurma.setEnabled(true);
        cbxTurma.removeAllItems();

        if (cbxCurso.getSelectedIndex() != -1) {
            daoCurso = new DaoCurso(conexao.conectar());

            String siglaCurso = (String) cbxCurso.getSelectedItem();
            Double valorCurso = daoCurso.consultar(siglaCurso).getValor();

            lblValor.setText(Double.toString(valorCurso));
        } else {
            lblValor.setText(null);
        }

        daoTurma = new DaoTurma(conexao.conectar());
        cbxTurma.setSelectedItem(null);
        /*
        ArrayList<String> listaTurmas;
        listaTurmas = daoTurma.listarTurmas((String) cbxCurso.getSelectedItem());

        for (String turmas : listaTurmas) {
            cbxTurma.addItem(turmas);
        }*/

        ArrayList<Turma> listaTurmas;
        listaTurmas = daoTurma.listarTurma((String) cbxCurso.getSelectedItem());

        for (Turma turmas : listaTurmas) {
            cbxTurma.addItem(turmas.getSiglaTurma());
        }
        cbxTurma.setSelectedIndex(-1);
        txtCPFAluno.setText("");
    }//GEN-LAST:event_cbxCursoItemStateChanged

    private void cbxTurmaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxTurmaItemStateChanged

        if (cbxTurma.getSelectedIndex() == -1) {
            txtCPFAluno.setEnabled(false);
            rbtAVista.setEnabled(false);
            rbtAPrazo.setEnabled(false);
            txtCPFAluno.setText("");
        } else {
            txtCPFAluno.setEnabled(true);
            txtCPFAluno.requestFocus();
            rbtAVista.setEnabled(true);
            rbtAPrazo.setEnabled(true);
            txtCPFAluno.setText("");
        }
    }//GEN-LAST:event_cbxTurmaItemStateChanged

    private void rbtAVistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtAVistaActionPerformed
        txtAgencia.setEnabled(true);
        txtNCheque.setEnabled(true);
        txtPreData.setEnabled(true);
        txtQtdeMensalidade.setEnabled(false);
        txtTaxaJuros.setEnabled(false);
        txtDtVencimento.setEnabled(false);
    }//GEN-LAST:event_rbtAVistaActionPerformed

    private void rbtAPrazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtAPrazoActionPerformed
        txtAgencia.setEnabled(false);
        txtNCheque.setEnabled(false);
        txtPreData.setEnabled(false);
        txtQtdeMensalidade.setEnabled(true);
        txtTaxaJuros.setEnabled(true);
        txtDtVencimento.setEnabled(true);
    }//GEN-LAST:event_rbtAPrazoActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        matricula = null;
        aluno = null;
        matricula = daoMatricula.consultar(txtCPFAluno.getText(), (String) cbxTurma.getSelectedItem());
        aluno = daoAluno.consultar(txtCPFAluno.getText());

        if (pessoa.validarCPF(txtCPFAluno.getText()) == true) {
            //CPF válido
            txtCPFAluno.requestFocus();

            if (aluno == null) {
                JOptionPane.showMessageDialog(null, "Aluno não cadastrado", "ERRO", JOptionPane.ERROR_MESSAGE);
                cbxCurso.setEnabled(true);
                cbxCurso.setSelectedIndex(-1);
                txtCPFAluno.setText("");
                txtAgencia.setText("");
                txtNCheque.setText("");
                txtPreData.setText("");
                txtQtdeMensalidade.setText("");
                txtTaxaJuros.setText("");
                txtDtVencimento.setText("");

                btnConsultar.setEnabled(true);
                btnInserir.setEnabled(false);
                btnAlterar.setEnabled(false);
                btnExcluir.setEnabled(false);

            } else {
                lblNomeAluno.setText(daoAluno.consultar(txtCPFAluno.getText()).getNome());
                if (matricula == null) {
                    cbxCurso.setEnabled(false);
                    cbxTurma.setEnabled(false);
                    txtCPFAluno.setEnabled(false);
                    txtDataMatricula.setEnabled(true);
                    txtDataMatricula.requestFocus();

                    btnConsultar.setEnabled(false);
                    btnInserir.setEnabled(true);
                    btnAlterar.setEnabled(false);
                    btnExcluir.setEnabled(false);

                } else {
                    cbxCurso.removeAllItems();
                    cbxTurma.removeAllItems();
                    cbxCurso.setSelectedItem(matricula.getTurma().getCurso().getSigla());
                    cbxTurma.setSelectedItem(matricula.getTurma().getSiglaTurma());
                    txtDataMatricula.setText(matricula.getData());
                    lblValor.setText(Double.toString(matricula.getTurma().getCurso().getValor()));
                    txtCPFAluno.setText(matricula.getAluno().getCpf());
                    lblNomeAluno.setText(matricula.getAluno().getNome());

                    cbxCurso.setEnabled(false);
                    cbxTurma.setEnabled(false);
                    txtCPFAluno.setEnabled(false);
                    txtDataMatricula.setEnabled(true);
                    txtDataMatricula.requestFocus();

                    btnConsultar.setEnabled(false);
                    btnInserir.setEnabled(false);
                    btnAlterar.setEnabled(true);
                    btnExcluir.setEnabled(true);
                }
            }

        } else {
            //CPF inválido
            JOptionPane.showMessageDialog(null, "CPF inválido", "ERRO", JOptionPane.ERROR_MESSAGE);
            txtDataMatricula.setText("");
            txtDataMatricula.requestFocus();
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed

        aluno = null;

        String dataMatricula = txtDataMatricula.getText();
        String cpfAluno = txtCPFAluno.getText();
        String siglaTurma = (String) cbxTurma.getSelectedItem();

        aluno = daoAluno.consultar(cpfAluno);
        turma = new Turma(siglaTurma, daoTurma.consultar(siglaTurma).getDescricao());
        matricula = new Matricula(dataMatricula);
        matricula.setAluno(aluno);
        matricula.setTurma(turma);

        if (rbtAVista.isSelected()) {
            aVista = new AVista();

            /*Tratamento de erros de Conversao de String vazia*/
            try {
                if (txtAgencia.getText() != null) {
                    aVista.setAgencia(Integer.parseInt(txtAgencia.getText()));
                }
            } catch (NumberFormatException e) {
                aVista.setAgencia(0);
            }

            try {
                if (txtNCheque.getText() != null) {
                    aVista.setNCheque(Integer.parseInt(txtNCheque.getText()));
                }
            } catch (NumberFormatException e) {
                aVista.setNCheque(0);
            }

            try {
                if (lblValor.getText() != null) {
                    aVista.setValor(Double.parseDouble(lblValor.getText()));
                }
            } catch (NumberFormatException e) {
                aVista.setValor(0.00);
            }

            //aVista.setAgencia(Integer.parseInt(txtAgencia.getText()));
            //aVista.setNCheque(Integer.parseInt(txtNCheque.getText()));
            //aVista.setValor(Double.parseDouble(lblValor.getText()));
            aVista.setCpf(cpfAluno);
            aVista.setDataMatricula(dataMatricula);
            aVista.setPreData(txtPreData.getText());
            aVista.setSiglaTurma(siglaTurma);
            matricula.setaVista(aVista);

            daoAVista.inserir(aVista);

        } else if (rbtAPrazo.isSelected()) {
            aPrazo = new APrazo();

            /*Tratamento de erros de Conversao de String vazia*/
            try {
                if (txtQtdeMensalidade.getText() != null) {
                    aPrazo.setQtdeMensalidade(Integer.parseInt(txtQtdeMensalidade.getText()));
                }
            } catch (NumberFormatException e) {
                aPrazo.setQtdeMensalidade(0);
            }

            try {
                if (txtTaxaJuros.getText() != null) {
                    aPrazo.setTaxaJuros(Double.parseDouble(txtTaxaJuros.getText()));
                }
            } catch (NumberFormatException e) {
                aPrazo.setTaxaJuros(0.00);
            }

            try {
                if (lblValor.getText() != null) {
                    aPrazo.setValor(Double.parseDouble(lblValor.getText()));
                }
            } catch (NumberFormatException e) {
                aPrazo.setValor(0.00);
            }

            //aPrazo.setQtdeMensalidade(Integer.parseInt(txtQtdeMensalidade.getText()));            
            //aPrazo.setTaxaJuros(Double.parseDouble(txtTaxaJuros.getText()));
            //aPrazo.setValor(Double.parseDouble(lblValor.getText()));
            aPrazo.setCpf(cpfAluno);
            aPrazo.setDataMatricula(dataMatricula);
            aPrazo.setDtVencimento(txtDtVencimento.getText());
            aPrazo.setSiglaTurma(siglaTurma);
            matricula.setaPrazo(aPrazo);

            daoAPrazo.inserir(aPrazo);
        }

        daoMatricula.inserir(matricula);

        txtDataMatricula.setText("");
        cbxCurso.setSelectedIndex(-1);
        cbxTurma.setSelectedIndex(-1);
        txtCPFAluno.setText("");
        txtAgencia.setText("");
        txtNCheque.setText("");
        txtPreData.setText("");
        txtQtdeMensalidade.setText("");
        txtTaxaJuros.setText("");
        txtDtVencimento.setText("");

        txtDataMatricula.setEnabled(true);
        txtCPFAluno.setEnabled(false);
        txtAgencia.setEnabled(false);
        txtNCheque.setEnabled(false);
        txtPreData.setEnabled(false);
        txtQtdeMensalidade.setEnabled(false);
        txtTaxaJuros.setEnabled(false);
        txtDtVencimento.setEnabled(false);

        txtDataMatricula.requestFocus();

        btnConsultar.setEnabled(true);
        btnInserir.setEnabled(false);
    }//GEN-LAST:event_btnInserirActionPerformed

    private void cbxTurmaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxTurmaFocusLost
        if (cbxTurma.getSelectedIndex() != -1) {
            txtCPFAluno.setEnabled(true);
            txtCPFAluno.setText("");
        }
    }//GEN-LAST:event_cbxTurmaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiAlocarEfetuarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiAlocarEfetuarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiAlocarEfetuarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiAlocarEfetuarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiAlocarEfetuarMatricula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair;
    private javax.swing.ButtonGroup btngrPagamento;
    private javax.swing.JComboBox<String> cbxCurso;
    private javax.swing.JComboBox<String> cbxTurma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNomeAluno;
    private javax.swing.JLabel lblValor;
    private javax.swing.JRadioButton rbtAPrazo;
    private javax.swing.JRadioButton rbtAVista;
    private javax.swing.JTextField txtAgencia;
    private javax.swing.JFormattedTextField txtCPFAluno;
    private javax.swing.JFormattedTextField txtDataMatricula;
    private javax.swing.JFormattedTextField txtDtVencimento;
    private javax.swing.JTextField txtNCheque;
    private javax.swing.JFormattedTextField txtPreData;
    private javax.swing.JTextField txtQtdeMensalidade;
    private javax.swing.JTextField txtTaxaJuros;
    // End of variables declaration//GEN-END:variables
    private Conexao conexao = null;
    private DaoCurso daoCurso = null;
    private DaoTurma daoTurma = null;
    private DaoAluno daoAluno = null;
    private Aluno aluno = null;
    private Pessoa pessoa = null;
    private Matricula matricula = null;
    private Turma turma = null;
    private AVista aVista = null;
    private APrazo aPrazo = null;
    private DaoMatricula daoMatricula = null;
    private DaoAVista daoAVista = null;
    private DaoAPrazo daoAPrazo = null;
}
